name: Reusable workflow for JASP unit tests

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (R ${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        r: [release]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REMOTES_UPGRADE: never
      VDIFFR_RUN_TESTS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      _R_CHECK_LENGTH_1_CONDITION_: TRUE #deprecated from R 4.2.0
      _R_CHECK_MATRIX_DATA_: TRUE # only works from R 4.2.0 onwards

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Install system dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          # Caught by https://github.com/actions/runner-images/issues/6817
          brew link --overwrite python@3.10
          brew install --cask xquartz
        shell: bash

      - name: Install system dependencies on macOS specific to R devel
        if: runner.os == 'macOS' && matrix.r == 'devel'
        run: |
          # ragg                                          requires harfbuzz fribidi
          # The dependencies of the two R packages below are required for compiling from source on Ubuntu, but macOS seems fine without them
          # credentials   (dependency of usethis)         requires libgit2
          # curl          (dependency of usethis)         requires openssl

          brew install harfbuzz fribidi libgit2 openssl curl
        shell: bash

      - name: Set environment variable to never compile packages on Windows and macOS
        if: runner.os != 'Linux' && matrix.r != 'devel'
        run: |
          # don't try to install new pkgs versions from source (which often requires additional system dependencies which, when missing, lead to errors, e.g., ragg).
          cat("\noptions(install.packages.compile.from.source = \"never\")\n", file = "~/.Rprofile", sep = "", append = TRUE)
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            github::jasp-stats/jaspTools
          needs: check
          cache-version: 2

      - name: Setup jaspTools
        run: |
          jaspTools::setupJaspTools()
        shell: Rscript {0}

      - name: Run unit tests
        run: source("tests/testthat.R")
        shell: Rscript {0}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact-${{ matrix.os }}
          path: tests/**/*.svg
